# SPDX-PackageName: finnix-tracker
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://forge.colobox.com/finnix/finnix-tracker
# SPDX-FileCopyrightText: © 2026 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0
---
when:
  - event: ["push", "pull_request", "manual"]
labels:
  platform: "linux/amd64"
clone:
  git:
    image: "docker.io/woodpeckerci/plugin-git:latest@sha256:ebde4a4d07e0e24b630082484d192890dd4f6d442d90bf5466f0763860f83652"  # 2026-05-28
steps:
  - name: "CI build"
    image: "docker.io/library/node:26-alpine@sha256:144769ec3f32e8ee36b3cfde91e82bee25d9367b20f31a151f3f7eea3a2a8541"  # 2026-06-01
    commands: |
      set -x

      cat <<"EOM" >~/.npmrc
      registry=http://omniproxi.snowman.lan/npm/
      EOM

      npm install
      npm test
  - name: "Notify Mastodon if failure"
    when:
      - status: ["failure"]
    image: "docker.io/woodpeckerci/plugin-mastodon-post:latest@sha256:456597681cff794b6ddb7b085ce95c42a18301e512503898c4abdaa1080e7e4c"  # 2026-04-19
    settings:
      server_url: "https://m29.us"
      access_token:
        from_secret: "m29_token"
      status: |
        🪿 🪿 🪿 FAILURE: {{ CI_REPO }} 🪿 🪿 🪿
        Workflow: {{ CI_WORKFLOW_NAME }} ({{ CI_PIPELINE_EVENT }} on {{ CI_COMMIT_REF }})

        Pipeline: {{ CI_PIPELINE_URL }}
        Commit: {{ CI_PIPELINE_FORGE_URL }}
