name: Build and push registry
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Build image
      run: docker image build -t ghcr.io/finnix/finnix-tracker:latest .
    - name: Push image
      run: docker image push ghcr.io/finnix/finnix-tracker:latest
